
#Configurations related to materials.
[materials]
	#Should the mod find ingot materials with ores.
	ingot = true
	#Should the mod find gem materials with ores.
	gem = true
	#Should the mod find crystal materials with ores.
	crystal = true
	#Should the mod find dust materials with ores.
	dust = true
	#Should the mod find ingot materials without ores.
	ingotPlain = true
	#Should the mod find gem materials without ores.
	gemPlain = true
	#Should the mod find crystal materials without ores.
	crystalPlain = true
	#Should the mod find dust materials without ores.
	dustPlain = true
	#Should the mod not find materials with ores with used prefixes.
	nonPlainUsedPrefix = false
	#Should the mod not find materials with used prefixes when the material name is not found yet.
	strictUsedPrefix = false

#Configurations related to material overrides.
[materialOverrides]
	#List of materials that should be gems.
	gem = ["Coal", "Diamond", "Emerald", "Lapis", "Prismarine", "Quartz"]
	#List of materials that should be crystals.
	crystal = ["Prosperity"]
	#List of materials that should be dusts.
	dust = ["Redstone"]

#Configurations related to item selection.
[itemSelection]
	#List of mods that are preferred when selecting items in recipes.
	preferredMods = ["minecraft", "jaopca"]

#Configurations related to the ore dictionary.
[oredict]
	#List of oredict names that should not be added.
	blacklist = ["FoolsGold", "Ashes"]
	#List of oredict modules that should not be registered.
	moduleBlacklist = []
	#List of custom oredict entries to add. Format: <mod:item@meta=oredict>
	custom = ["thaumictinkerer:kamiresource@3=ingotIchorium", "thaumictinkerer:kamiresource@5=nuggetIchorium", "deepmoblearning:glitch_infused_ingot@0=ingotGlitch", "aetherworks:item_resource@4=ingotAether", "aetherworks:block_aether@0=blockAether", "aetherworks:item_resource@0=nuggetAether", "calculator:reinforcedironingot@0=ingotReinforcedIron", "calculator:material@3=blockReinforcedIron", "calculator:redstoneingot@0=ingotReinforcedRedstone", "calculator:material@9=blockReinforcedRedstone", "naturesaura:infused_iron@0=ingotInfusedIron", "naturesaura:infused_iron_block@0=blockInfusedIron", "naturesaura:sky_ingot@0=ingotSky", "twilightforest:steeleaf_ingot@0=ingotSteelleaf", "twilightforest:block_storage@2=blockSteelleaf", "theaurorian:auroriansteelblock@0=blockAurorianSteel", "theaurorian:auroriansteel@0=ingotAurorianSteel", "theaurorian:auroriansteelnugget@0=nuggetAurorianSteel", "theaurorian:ceruleanore@0=oreCerulean", "theaurorian:ceruleanblock@0=blockCerulean", "theaurorian:ceruleaningot@0=ingotCerulean", "theaurorian:ceruleannugget@0=nuggetCerulean", "theaurorian:moonstoneore@0=oreMoonstone", "theaurorian:moonstoneblock@0=blockMoonstone", "theaurorian:moonstoneingot@0=ingotMoonstone", "theaurorian:moonstonenugget@0=nuggetMoonstone", "theaurorian:aurorianiteingot@0=ingotAurorianite", "theaurorian:scrapaurorianite@0=nuggetAurorianite", "theaurorian:crystallineingot@0=ingotCrystalline", "theaurorian:scrapcrystalline@0=nuggetCrystalline", "theaurorian:umbraingot@0=ingotUmbra", "theaurorian:scrapumbra@0=nuggetUmbra", "soot:ingot_antimony@0=ingotAntinomy", "industrialforegoing:pink_slime_ingot@0=ingotPinkSlime", "threng:material@0=ingotFluixSteel", "bloodarsenal:base_item@4=ingotBloodInfusedIron", "bloodarsenal:blood_infused_iron_block@=blockBloodInfusedIron", "contenttweaker:cold_ingot@0=ingotCold", "contenttweaker:useful_ingot@0=ingotUseful", "contenttweaker:useful_block@0=blockUseful", "mysticalagriculture:crafting@5=crystalProsperity", "mysticalagriculture:storage@5=blockProsperity", "thaumicbases:thauminite_plate@0=plateThauminite", "thaumicbases:nuggetthauminite@0=nuggetThauminite", "thaumicbases:thauminite_ingot@0=ingotThauminite", "thaumicbases:blockthauminite@0=blockThauminite", "appliedenergistics2:fluix_block@0=blockFluix", "appliedenergistics2:quartz_block@0=blockCertusQuartz", "thaumicrestoration:item_ingot@0=ingotThaumiumAer", "thaumicrestoration:item_plate@0=plateThaumiumAer", "thaumicrestoration:item_ingot@1=ingotThaumiumIgnis", "thaumicrestoration:item_plate@1=plateThaumiumIgnis", "thaumicrestoration:item_ingot@2=ingotThaumiumAqua", "thaumicrestoration:item_plate@2=plateThaumiumAqua", "thaumicrestoration:item_ingot@3=ingotThaumiumTerra", "thaumicrestoration:item_plate@3=plateThaumiumTerra", "thaumicrestoration:item_ingot@4=ingotThaumiumOrdo", "thaumicrestoration:item_plate@4=plateThaumiumOrdo", "thaumicrestoration:item_ingot@5=ingotThaumiumPerditio", "thaumicrestoration:item_plate@5=plateThaumiumPerditio", "tconevo:metal_block@7=blockEnergium"]

#Configurations related to recipes.
[recipes]
	#List of recipes that should not be added.
	blacklist = []
	#List of recipes by regex that should not be added.
	regexBlacklist = []

#Configurations related to color generation.
[colors]
	#The gamma value used to blend colors.
	gammaValue = 2.0
	#Should colors of all materials be reset on next startup.
	resetColors = false

#Configurations related to material localization.
[materialLocalization]
	#Should the mod check for material localization updates.
	checkL10nUpdates = false
	#The update interval of localization files in days.
	updateInterval = 3.0

