
#Configurations for material Curium246Carbide.
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 3681324

[mysticalagriculture]
	#The crop tier of this material.
	tier = 3
	#The amount of Mystical Agriculture essence required to craft materials.
	inputCount = 8
	#The amount of material obtained by crafting Mystical Agriculture essence.
	outputCount = 4

[avaritia]
	#The base amount of blocks required to create one singularity.
	inputAmount = 300
	#Should the singularity be added to the Infinity Catalyst recipe.
	addToCatalyst = true

[thermalexpansion_mysticalagriculture]
	#The base seed output chance when growing Mystical Agriculture seeds in Thermal Expansion's Insolator with Phyto-Gro.
	basicChance = 100
	#The base seed output chance when growing Mystical Agriculture seeds in Thermal Expansion's Insolator with Rich Phyto-Gro.
	richChance = 105
	#The base seed output chance when growing Mystical Agriculture seeds in Thermal Expansion's Insolator with Fluxed Phyto-Gro.
	fluxChance = 110

