
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "crystal"
	#The color of this material.
	color = 1118223
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = true

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "minecraft:cobblestone"

[avaritia]
	#The base amount of blocks required to create one singularity.
	inputAmount = 300
	#Should the singularity be added to the Infinity Catalyst recipe.
	addToCatalyst = true

